### ISSUE TITLE
How did you measure the IS score?

### ISSUE THREAD

**Issue by JiwanHur** [LeapLabTHU/ImprovedNAT#1]
Thank you for the great work!

I tried to measure the IS score based on the provided checkpoint.
The FID was 2.57, which is similar to the report in the paper.
However, I got an IS of 322.90, which was way higher than the value in the paper (278.8).

I use the same Inception network provided, and the weight of the last fc layer for IS is from the link below.
(https://github.com/openai/improved-gan/blob/4f5d1ec5c16a7eceb206f42bfc652693601e1d5c/inception_score/model.py).

Could you provide a codebase for measuring the IS score used in the paper? 
Thank you!

**Comment by nzl-thu** [comment]
Hi, sorry for the late reply.

We use the `torch_fidelity` library to calculate the IS score. We are not sure if there is any difference compared to the code you provided.

Moreover, the released code is a re-implemented and cleaned-up version of our original code. The configurations obtained may be slightly better than the results reported in our original paper :)
